# algorithms-python
Learning Algorithms using python.

#Bubble Sort Algorithm

Bubble Sort is a simple sorting algorithm that compares adjacent elements in a list or an array and swaps them if they are in the wrong order. This process is repeated until the entire list is sorted. Bubble Sort has a time complexity of O(n^2) and is not considered efficient for large datasets.

Here's an example of how the Bubble Sort algorithm works:

We start by comparing the first two elements of the list. If the first element is larger than the second element, we swap them.

We then compare the second and third elements of the list. If the second element is larger than the third element, we swap them.

We continue this process, comparing and swapping adjacent elements until we reach the end of the list.

Once we have reached the end of the list, we repeat the entire process again, starting from the beginning of the list, until the entire list is sorted.

Here's an example implementation of Bubble Sort in Python:

[source,python]
----
def sort(A):
    for i in range(len(A) - 1, 0, -1):
        for j in range(0, i):
            
            if A[j] > A[j + 1]:
                A[j], A[j + 1] = A[j + 1], A[j]


li = []

for i in range(8):
    li.append(int(input("Enter Number: ")))


sort(li)
print(li)
----

#Selection Sort Algorithm
[source,python]
----
def selection_sort(arr):
    for i in range(0, len(arr) - 1):
        min = i
        for j in range(i + 1, len(arr)):
            if(arr[j] < arr[min]):
               min  = j

        arr[i], arr[min] = arr[min], arr[i]


arr = [2, 6, 5, 1, 3, 4]

selection_sort(arr)

print(arr)

----



#Insertion sort
[source,python]
----
def insertionSort(A):
    for i in range(1, len(A)):
        j = i
        while A[j-1] > A[j] and j > 0:
            A[j-1], A[j] = A[j], A[j-1]
            j -= 1

A = [2,7,4,1,3,8,5,9,6]
insertionSort(A)
print(A)

----


#Quick Sort

[source,python]
----

def quickSort(A, left, right):
    if left < right:
        part = partition(A, left, right)
        quickSort(A, left, part - 1)
        quickSort(A, part + 1, right)

def partition(A, left, right):
    i = left
    j = right - 1
    pivot = A[right]

    while i < j:
        while i < right and A[i] < pivot:
            i += 1
        while j > left and A[j] > pivot:
            j -= 1

        if i < j:
            A[i], A[j] = A[j], A[i]

    if A[i] > pivot:
        A[i], A[right] = A[right], A[i]

    return i
            


A = [12,45,34,76,89,43,56]
quickSort(A, 0, len(A) - 1)
print(A)

----
   
